name = "sub-elite-api"
main = "worker/index.js"
compatibility_date = "2026-05-10"
workers_dev = true
preview_urls = false

[[kv_namespaces]]
binding = "SUBSCRIPTIONS"
id = "65fd37b0b58e46e89b4caaf06425199a"
